name: property_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0-265.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.3
  intl: ^0.17.0
  carousel_slider: 4.1.1
  image_picker: 0.8.5+3
  firebase_core: ^1.17.0
  cloud_firestore: 3.1.15
  firebase_storage: 10.2.16
  flutter_phone_direct_caller: ^2.1.1
  share_plus: ^4.0.4
  google_maps_flutter:
  http:
  geolocator:
  whatsapp_unilink: ^2.0.1+1
  razorpay_flutter: ^1.3.0
  geocoding: ^2.0.4
  image_picker_web: ^2.1.1
  google_place:
  url_launcher:
  flutter_sms: ^2.3.2
  path_provider:
  firebase_auth:
  flutter_native_splash: ^2.2.1
  syncfusion_flutter_pdf: ^20.1.58-beta
  open_file: ^3.2.1
  flutter: 
    sdk: flutter
  csc_picker: ^0.2.6

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app/Image-4.png"
  remove_alpha_ios: true

  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/bold/
    - assets/home/
    - assets/payment/
    - assets/profile/
    - assets/app/
    - assets/admin/
    - assets/filter/
  fonts: 
    - family: Arial
      fonts: 
        - asset: fonts/arial-Regular.ttf
  uses-material-design: true

